### ISSUE TITLE
Users management [microservice]

### ISSUE THREAD

**Issue by vitalygrishin27** [vitalygrishin27/microservice-grade-book#6]

**Comment by vitalygrishin27** [comment]
Version Service 1.2.0

**Comment by iprokhorenko13** [comment]
Create the next requests:
Get
Post (+check in database)
Put (+check in database)
Delete (+check in database)

**Comment by iprokhorenko13** [comment]
The task will be completed within the scope of the task: https://github.com/vitalygrishin27/microservice-grade-book/issues/14
